output "app_secret_arn" {
  value       = aws_secretsmanager_secret.app.arn
  description = "ARN of the application secret (value generated by Terraform random provider)."
}

output "app_secret_name" {
  value = aws_secretsmanager_secret.app.name
}
